apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-access-mismatch
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/pv-access-mismatch"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-access-mismatch
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteMany  # Mismatched access mode
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-access-mismatch
spec:
  containers:
  - name: app
    image: nginx
    volumeMounts:
    - mountPath: "/usr/share/nginx/html"
      name: storage
  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: pvc-access-mismatch
