apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-binding-issues
  labels:
    storage-tier: gold
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/pv-binding-issues"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-binding-issues
spec:
  selector:
    matchLabels:
      storage-tier: silver  # Label mismatch with the PV
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-binding-issues
spec:
  containers:
  - name: app
    image: nginx
    volumeMounts:
    - mountPath: "/usr/share/nginx/html"
      name: storage
  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: pvc-binding-issues
