apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-storage-exhaustion
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/pv-storage-exhaustion"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-storage-exhaustion
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-storage-exhaustion
spec:
  containers:
  - name: app
    image: nginx
    volumeMounts:
    - mountPath: "/usr/share/nginx/html"
      name: storage
  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: pvc-storage-exhaustion